name: Scrape Jobs Every 20 Minutes

on:
  schedule:
    # Runs every 20 minutes (at 0, 20, 40 past the hour)
    - cron: '*/20 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests beautifulsoup4
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push jobs.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add jobs.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update jobs.json [$(date)]" && git push)
